name: C I
on: 
  pull_request:
    branches:
      ['master']
##jobs
jobs:
  ##nome
  continuos-integration:
  ##maquina virtual
  runs-on: ubuntu-latest

  steps:
    ##clonando a branhc
    - uses: action/checkout@v3
    - name: usando Nodejs
      uses: action/setup-node@v2
      with:
        node-version:16.x
    - name: run install, build and test
      run: |
        npm install
        npm run build 
        npm run test
